apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codewinds.codewind.eclipse.org
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.username
    description: Deployment reference name
    name: Username
    type: string
  - JSONPath: .metadata.namespace
    description: Deployment namespace
    name: Namespace
    type: string
  - JSONPath: .metadata.annotations.codewindWorkspace
    description: WorkspaceID
    name: Workspace
    type: string
  - JSONPath: .metadata.creationTimestamp
    description: Age of the resource
    name: Age
    type: date
  - JSONPath: .spec.keycloakDeployment
    description: Deployment reference name
    name: Keycloak
    type: string
  - JSONPath: .status.keycloakStatus
    description: Keycloak configuration status
    name: Registration
    type: string
  - JSONPath: .status.accessURL
    description: Exposed route
    name: AccessURL
    type: string
  group: codewind.eclipse.org
  names:
    kind: Codewind
    listKind: CodewindList
    plural: codewinds
    singular: codewind
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Codewind is the Schema for the codewinds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CodewindSpec defines the desired state of Codewind
          properties:
            keycloakDeployment:
              description: 'KeycloakDeployment : name of the keycloak deployment used
                by this instance of codewind'
              pattern: ^[A-Za-z0-9/-]*$
              type: string
            logLevel:
              description: LogLevel within pods
              type: string
            storageSize:
              description: Codewind Storage size
              pattern: '[0-9]*Gi$'
              type: string
            username:
              description: Developer username assigned to this instance
              pattern: ^[A-Za-z0-9/-]*$
              type: string
          required:
          - keycloakDeployment
          - logLevel
          - storageSize
          - username
          type: object
        status:
          description: CodewindStatus defines the observed state of Codewind
          properties:
            accessURL:
              description: Exposed Ingress of Codewind (Gatekeeper)
              type: string
            authURL:
              description: 'Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Keycloak access URL'
              type: string
            keycloakStatus:
              description: Keycloak Configuration status
              type: string
          required:
          - accessURL
          - authURL
          - keycloakStatus
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
