kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: codewind-operator
subjects:
  - kind: ServiceAccount
    name: codewind-operator
    namespace: codewind
roleRef:
  kind: ClusterRole
  name: codewind-operator
  apiGroup: rbac.authorization.k8s.io